version: '3'

services:
  db:
    container_name: db
    image: postgres:12.2-alpine
    restart: always
    environment:
      POSTGRES_DB: nice_marmot
      POSTGRES_USER: runner
      POSTGRES_PASSWORD: ""
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 5433:5432
  web:
    container_name: web
    build: .
    command: bash -c "
        pip install requests
        && pip install django-cors-headers
        && mkdir -p /shared/plotting
        && mkdir -p /shared/machinelearning
        && mkdir -p /shared/classification
        && rm /code/djangoweb/api/static/plots -rf
        && ln -s /code/shared /code/djangoweb/api/static/plots
        && python /code/djangoweb/manage.py makemigrations api
        && python /code/djangoweb/manage.py runserver 0.0.0.0:8080
      "
    volumes:
      - .:/code
      - ./shared:/shared
    ports:
      - 80:8080
    restart: always
    depends_on:
      - db
  node_auth_server:
    container_name: node_auth_server
    build: ./node_auth_server
    image: node:8
    restart: always
    command: bash -c "
      cd /node_auth_server
      && npm install
      && npm install bcrypt
      && npm run migrate
      && npm start
      "
    volumes:
      - ./node_auth_server:/node_auth_server
      - ./shared:/shared
    ports:
      - 8090:8090
  basicanalysis:
    container_name: basicanalysis
    build: ./basicanalysis
    image: alikth/basic_cell:latest
    restart: always
    command: bash -c "
        pip install -r requirements.txt
        && python3.6 api.py
      "
    volumes:
      - ./basicanalysis:/usr/src/app
      - ./shared:/shared
    ports:
      - 3000:3000
    depends_on:
      - web
  plotting:
    container_name: plotting
    build: ./plotting
    image: alikth/basic_cell:latest
    restart: always
    command: bash -c "
        pip install -r requirements.txt
        && python3.6 api.py
      "
    volumes:
      - ./plotting:/usr/src/app
      - ./shared:/shared
    ports:
      - 4000:4000
    depends_on:
      - web
  machinelearning:
    container_name: machinelearning
    build:
      context: ./machinelearning
    image:  alikth/ml_cell:latest
    restart: always
    command: bash -c "
      pip install -r requirements.txt
      && pip3 uninstall bottleneck -y
      && pip3 install bottleneck==1.2
      && python3.6 api.py
      "
    volumes:
      - ./machinelearning:/usr/src/app
      - ./shared:/shared
    ports:
      - 5000:5000
    depends_on:
      - web
  classification:
    container_name: classification
    build:
      context: ./classification
    image:  alikth/ml_cell:latest
    restart: always
    command: bash -c "
      pip install -r requirements.txt
      && pip3 uninstall bottleneck -y
      && pip3 install bottleneck==1.2
      && python3.6 api.py
      "
    volumes:
      - ./classification:/usr/src/app
      - ./shared:/shared
    ports:
      - 6000:6000
    depends_on:
      - web
