# Generated by Django 3.0.3 on 2020-02-19 18:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 19, 18, 10, 45, 641475, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='model',
            name='filename',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='model',
            name='plot_paths',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='model',
            name='results',
            field=models.TextField(default=''),
        ),
    ]
