# Generated by Django 3.0.3 on 2020-02-19 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20200219_1810'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model',
            name='date',
        ),
        migrations.AddField(
            model_name='model',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='model',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
