# Generated by Django 2.2.12 on 2020-05-23 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(default='', max_length=100)),
                ('results', models.TextField(default='')),
                ('plot_paths', models.TextField(default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='tbmeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.TextField(default='NA', max_length=100, null=True)),
                ('category', models.TextField(default='admin', max_length=50, null=True)),
                ('recorddate', models.DateTimeField(auto_now_add=True, null=True)),
                ('uploaddate', models.DateTimeField(auto_now_add=True, null=True)),
                ('filename', models.TextField(default='', max_length=100)),
                ('uploadname', models.TextField(default='', max_length=100)),
                ('channels', models.CharField(default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': '"tbmeta"',
            },
        ),
        migrations.CreateModel(
            name='tbusers',
            fields=[
                ('userid', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(default='', max_length=100)),
                ('password', models.TextField(default='', max_length=100)),
                ('fullname', models.TextField(default='', max_length=100)),
                ('trials', models.IntegerField(default=0)),
                ('locked', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('mobilephone', models.TextField(default='NA', max_length=20, null=True)),
                ('usergroup', models.TextField(default='admin', max_length=50, null=True)),
                ('location', models.TextField(default='NA', max_length=100, null=True)),
                ('locationdescription', models.TextField(default='NA', max_length=1000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': '"tbusers"',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(default='', max_length=100)),
                ('password', models.TextField(default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('filename_1', models.CharField(default='', max_length=100)),
                ('filename_2', models.CharField(default='', max_length=100)),
                ('filename_3', models.CharField(default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
